name: CI/CD Pipeline for AI Face Recognition

on:
  push:
    branches:
      - main  # Trigger this workflow when there is a push to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Set up an Ubuntu-based runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out your repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Set up Docker Buildx

      - name: Login to DockerHub
        uses: docker/login-action@v3  # Login to DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Username from GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Password from GitHub Secrets

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5  # Build and push Docker image
        with:
          context: .  # Build from the root of the repository
          push: true  # Push the image to DockerHub
          tags: adhithya143/ai-face-recognition:latest  # Use your DockerHub username and tag
